# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SERVICOS", "Relatório de Serviços"),
                            ("FATURAMENTO", "Relatório de Faturamento"),
                            ("CLIENTES", "Relatório de Clientes"),
                            ("FUNCIONARIOS", "Relatório de Funcionários"),
                            ("AGENDAMENTOS", "Relatório de Agendamentos"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "formato",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel"), ("CSV", "CSV")],
                        default="PDF",
                        max_length=10,
                        verbose_name="Formato",
                    ),
                ),
                (
                    "data_geracao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Geração"
                    ),
                ),
                (
                    "filtros",
                    models.JSONField(
                        default=dict,
                        help_text="Filtros aplicados ao relatório em formato JSON",
                        verbose_name="Filtros",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="relatorios/%Y/%m/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "administrador",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "ADMINISTRADOR"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório",
                "verbose_name_plural": "Relatórios",
                "db_table": "relatorios",
                "ordering": ["-data_geracao"],
                "indexes": [
                    models.Index(
                        fields=["administrador", "data_geracao"],
                        name="relatorios_adminis_0effd3_idx",
                    ),
                    models.Index(
                        fields=["tipo", "data_geracao"],
                        name="relatorios_tipo_f1b1c7_idx",
                    ),
                ],
            },
        ),
    ]
