# Generated by Django 4.2.11 on 2026-02-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("relatorios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="administrador",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "ADMINISTRADOR"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relatorios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrador",
            ),
        ),
    ]
