# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("ATENDENTE", "Atendente"),
                            ("TOSADOR", "Tosador"),
                            ("VETERINARIO", "Veterinário"),
                            ("GERENTE", "Gerente"),
                        ],
                        max_length=20,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "horario_trabalho",
                    models.CharField(
                        help_text="Ex: Segunda a Sexta, 08:00-17:00",
                        max_length=100,
                        verbose_name="Horário de Trabalho",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funcionario",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionário",
                "verbose_name_plural": "Funcionários",
                "db_table": "funcionarios",
                "ordering": ["usuario__nome"],
                "indexes": [
                    models.Index(
                        fields=["cargo", "ativo"], name="funcionario_cargo_cb74ec_idx"
                    )
                ],
            },
        ),
    ]
