# Generated by Django 4.2.11 on 2026-03-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("funcionarios", "0002_horariotrabalho"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoFuncionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text="Identificador único do cargo (ex: VETERINARIO)",
                        max_length=50,
                        unique=True,
                        verbose_name="Valor (chave)",
                    ),
                ),
                (
                    "nome_display",
                    models.CharField(
                        help_text="Nome legível do cargo (ex: Veterinário)",
                        max_length=100,
                        verbose_name="Nome de exibição",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
            ],
            options={
                "verbose_name": "Cargo de Funcionário",
                "verbose_name_plural": "Cargos de Funcionário",
                "db_table": "cargos_funcionario",
                "ordering": ["nome_display"],
            },
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="cargo",
            field=models.CharField(max_length=50, verbose_name="Cargo"),
        ),
    ]
