# Generated by Django 4.2.11 on 2026-02-03 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pagamentos", "0001_initial"),
        ("agendamentos", "0002_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "data_atendimento",
                    models.DateTimeField(verbose_name="Data do Atendimento"),
                ),
                (
                    "tipo_servico",
                    models.CharField(max_length=100, verbose_name="Tipo de Serviço"),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre o atendimento realizado",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor Pago",
                    ),
                ),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos",
                        to="pagamentos.formapagamento",
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_atendimentos",
                        to="pets.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico de Atendimento",
                "verbose_name_plural": "Históricos de Atendimento",
                "db_table": "historico_atendimentos",
                "ordering": ["-data_atendimento"],
                "indexes": [
                    models.Index(
                        fields=["pet", "data_atendimento"],
                        name="historico_a_pet_id_f4815a_idx",
                    ),
                    models.Index(
                        fields=["data_atendimento"],
                        name="historico_a_data_at_6d4fc9_idx",
                    ),
                ],
            },
        ),
    ]
