# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato: 000.000.000-00",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                ("endereco", models.CharField(max_length=255, verbose_name="Endereço")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CE", "Ceará"),
                            ("PI", "Piauí"),
                            ("RN", "Rio Grande do Norte"),
                        ],
                        default="CE",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cep",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve estar no formato: 00000-000",
                                regex="^\\d{5}-\\d{3}$",
                            )
                        ],
                        verbose_name="CEP",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["usuario__nome"],
                "indexes": [
                    models.Index(fields=["cpf"], name="clientes_cpf_977912_idx"),
                    models.Index(
                        fields=["cidade", "estado"], name="clientes_cidade_18ce72_idx"
                    ),
                ],
            },
        ),
    ]
