# Generated by Django 4.2.11 on 2026-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="ponto_referencia",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Ponto de Referência",
            ),
        ),
    ]
