# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        help_text="Data e hora do agendamento",
                        verbose_name="Data e Hora",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADO", "Agendado"),
                            ("CONFIRMADO", "Confirmado"),
                            ("EM_ANDAMENTO", "Em Andamento"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                            ("NAO_COMPARECEU", "Não Compareceu"),
                        ],
                        default="AGENDADO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre o agendamento",
                        verbose_name="Observações",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
                "db_table": "agendamentos",
                "ordering": ["-data_hora"],
            },
        ),
    ]
