# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("pagamentos", "0001_initial"),
        ("funcionarios", "0001_initial"),
        ("servicos", "0001_initial"),
        ("agendamentos", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="clientes.cliente",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="forma_pagamento",
            field=models.ForeignKey(
                help_text="Forma de pagamento escolhida no momento do agendamento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="pagamentos.formapagamento",
                verbose_name="Forma de Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="funcionario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agendamentos",
                to="funcionarios.funcionario",
                verbose_name="Funcionário Responsável",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="pets.pet",
                verbose_name="Pet",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agendamentos",
                to="servicos.servico",
                verbose_name="Serviço",
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["data_hora", "status"], name="agendamento_data_ho_bb202f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["cliente", "data_hora"], name="agendamento_cliente_228b12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["pet", "data_hora"], name="agendamento_pet_id_89b7d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agendamento",
            index=models.Index(
                fields=["funcionario", "data_hora"],
                name="agendamento_funcion_82ec60_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agendamento",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["AGENDADO", "CONFIRMADO", "EM_ANDAMENTO"])
                ),
                fields=("data_hora", "funcionario"),
                name="unique_funcionario_horario",
            ),
        ),
    ]
