# Generated by Django 4.2.11 on 2026-03-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="duracao_real",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duração efetiva considerando o porte do pet. Calculada ao criar.",
                null=True,
                verbose_name="Duração Real (min)",
            ),
        ),
    ]
