# Generated by Django 4.2.11 on 2026-03-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agendamentos", "0003_add_duracao_real"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendamento",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PAGO", "Pago"),
                    ("FALHOU", "Falhou"),
                ],
                default="PENDENTE",
                max_length=20,
                verbose_name="Status do Pagamento",
            ),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="valor_pago",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Valor Pago",
            ),
        ),
    ]
