# Generated by Django 4.2.11 on 2026-02-03 18:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="Nome"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("CARTAO_DEBITO", "Cartão de Débito"),
                            ("CARTAO_CREDITO", "Cartão de Crédito"),
                            ("PIX", "PIX"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Forma de Pagamento",
                "verbose_name_plural": "Formas de Pagamento",
                "db_table": "formas_pagamento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="TransacaoPagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valor_recebido",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor em dinheiro recebido do cliente",
                        max_digits=10,
                        null=True,
                        verbose_name="Valor Recebido",
                    ),
                ),
                (
                    "troco",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Valor do troco devolvido",
                        max_digits=10,
                        null=True,
                        verbose_name="Troco",
                    ),
                ),
                (
                    "pix_qrcode",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qrcodes/%Y/%m/",
                        verbose_name="QR Code PIX",
                    ),
                ),
                (
                    "pix_codigo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Código PIX Copia e Cola"
                    ),
                ),
                (
                    "pix_txid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "numero_transacao",
                    models.CharField(
                        blank=True,
                        help_text="Número da transação na maquininha",
                        max_length=100,
                        null=True,
                        verbose_name="Número da Transação",
                    ),
                ),
                (
                    "bandeira_cartao",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Visa, Mastercard, Elo",
                        max_length=50,
                        null=True,
                        verbose_name="Bandeira do Cartão",
                    ),
                ),
                (
                    "ultimos_digitos",
                    models.CharField(
                        blank=True,
                        max_length=4,
                        null=True,
                        verbose_name="Últimos 4 Dígitos",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "agendamento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamento",
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transacoes",
                        to="pagamentos.formapagamento",
                        verbose_name="Forma de Pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação de Pagamento",
                "verbose_name_plural": "Transações de Pagamento",
                "db_table": "transacoes_pagamento",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["agendamento"], name="transacoes__agendam_a62ffa_idx"
                    ),
                    models.Index(
                        fields=["status", "data_pagamento"],
                        name="transacoes__status_2f47cc_idx",
                    ),
                ],
            },
        ),
    ]
