# Generated by Django 4.2.11 on 2026-02-03 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BANHO", "Banho"),
                            ("TOSA", "Tosa"),
                            ("BANHO_TOSA", "Banho e Tosa"),
                            ("VETERINARIO", "Atendimento Veterinário"),
                            ("VACINA", "Vacinação"),
                            ("CONSULTA", "Consulta"),
                            ("EMERGENCIA", "Emergência"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Preço",
                    ),
                ),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        help_text="Duração estimada do serviço",
                        verbose_name="Duração em Minutos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "db_table": "servicos",
                "ordering": ["tipo"],
            },
        ),
    ]
