# Generated by Django 4.2.11 on 2026-02-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("BANHO", "Banho"),
                    ("TOSA", "Tosa"),
                    ("BANHO_TOSA", "Banho e Tosa"),
                    ("VETERINARIO", "Atendimento Veterinário"),
                    ("VACINA", "Vacinação"),
                    ("CONSULTA", "Consulta"),
                    ("EMERGENCIA", "Emergência"),
                ],
                max_length=20,
                verbose_name="Tipo de Serviço",
            ),
        ),
    ]
