# Generated by Django 4.2.11 on 2026-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicos", "0002_alter_servico_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="duracao_medio_grande",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Duração para porte médio/grande. Se vazio, usa a padrão.",
                null=True,
                verbose_name="Duração Médio/Grande (min)",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="duracao_minutos",
            field=models.PositiveIntegerField(
                help_text="Duração padrão do serviço (porte pequeno)",
                verbose_name="Duração em Minutos",
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("BANHO", "Banho"),
                    ("TOSA", "Tosa"),
                    ("BANHO_TOSA", "Banho e Tosa"),
                    ("CORTE_UNHAS", "Corte de Unhas"),
                    ("BANHO_TERAPEUTICO", "Banho Terapêutico"),
                    ("VETERINARIO", "Atendimento Veterinário"),
                    ("VACINA", "Vacinação"),
                    ("CONSULTA", "Consulta"),
                    ("EMERGENCIA", "Emergência"),
                ],
                max_length=20,
                verbose_name="Tipo de Serviço",
            ),
        ),
    ]
