# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agendamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CONFIRMACAO", "Confirmação de Agendamento"),
                            ("LEMBRETE", "Lembrete de Agendamento"),
                            ("CANCELAMENTO", "Cancelamento de Agendamento"),
                            ("CONCLUSAO", "Conclusão de Serviço"),
                            ("REAGENDAMENTO", "Reagendamento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("SMS", "SMS"),
                            ("AMBOS", "E-mail e SMS"),
                        ],
                        default="EMAIL",
                        max_length=10,
                        verbose_name="Canal",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        help_text="E-mail ou telefone do destinatário",
                        max_length=255,
                        verbose_name="Destinatário",
                    ),
                ),
                ("assunto", models.CharField(max_length=200, verbose_name="Assunto")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                ("enviada", models.BooleanField(default=False, verbose_name="Enviada")),
                (
                    "lida",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a notificação foi visualizada pelo usuário",
                        verbose_name="Lida",
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "tentativas",
                    models.PositiveIntegerField(default=0, verbose_name="Tentativas"),
                ),
                (
                    "erro",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro caso o envio falhe",
                        verbose_name="Erro",
                    ),
                ),
                (
                    "agendamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="agendamentos.agendamento",
                        verbose_name="Agendamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "notificacoes",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(
                        fields=["agendamento", "tipo"],
                        name="notificacoe_agendam_60f20d_idx",
                    ),
                    models.Index(
                        fields=["enviada", "data_criacao"],
                        name="notificacoe_enviada_48fc27_idx",
                    ),
                ],
            },
        ),
    ]
