# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "Já existe um usuário com este email."
                        },
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome Completo"),
                ),
                (
                    "telefone",
                    models.CharField(
                        help_text="Formato: (88) 99999-9999",
                        max_length=15,
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Foto de perfil do usuário",
                        null=True,
                        upload_to="usuarios/fotos/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("CLIENTE", "Cliente"),
                            ("FUNCIONARIO", "Funcionário"),
                            ("ADMINISTRADOR", "Administrador"),
                        ],
                        default="CLIENTE",
                        max_length=20,
                        verbose_name="Tipo de Usuário",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "usuarios",
                "ordering": ["-data_criacao"],
                "indexes": [
                    models.Index(fields=["email"], name="usuarios_email_0ff7b3_idx"),
                    models.Index(
                        fields=["tipo_usuario", "ativo"],
                        name="usuarios_tipo_us_79a990_idx",
                    ),
                ],
            },
        ),
    ]
