# Generated by Django 4.2.11

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_migrate_tipo_usuario_to_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
