# Generated by Django 4.2.11 on 2026-02-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_remove_usuario_tipo_usuario"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_tipo_us_79a990_idx",
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(fields=["ativo"], name="usuarios_ativo_2348b6_idx"),
        ),
    ]
