# Generated by Django 4.2.11 on 2026-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_usuario_usuarios_tipo_us_79a990_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="usuario",
            name="usuarios_ativo_2348b6_idx",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="ativo",
            new_name="is_active",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Formato: (88) 99999-9999",
                max_length=20,
                verbose_name="Telefone",
            ),
        ),
        migrations.AddIndex(
            model_name="usuario",
            index=models.Index(
                fields=["is_active"], name="usuarios_is_acti_8ee55c_idx"
            ),
        ),
    ]
