# Generated by Django 4.2.11 on 2026-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_remove_usuario_usuarios_ativo_2348b6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil do usuário",
                null=True,
                upload_to="perfil/fotos/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
