# Generated by Django 4.2.11 on 2026-02-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização",
                        verbose_name="Data de Atualização",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o registro está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "data_exclusao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora da exclusão lógica",
                        null=True,
                        verbose_name="Data de Exclusão",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("CAO", "Cão"),
                            ("GATO", "Gato"),
                            ("PASSARO", "Pássaro"),
                            ("COELHO", "Coelho"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=10,
                        verbose_name="Espécie",
                    ),
                ),
                ("raca", models.CharField(max_length=100, verbose_name="Raça")),
                (
                    "idade",
                    models.PositiveIntegerField(
                        help_text="Idade em anos", verbose_name="Idade"
                    ),
                ),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Peso em quilogramas",
                        max_digits=5,
                        verbose_name="Peso",
                    ),
                ),
                (
                    "porte",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MINI", "Mini (até 5kg)"),
                            ("PEQUENO", "Pequeno (5-10kg)"),
                            ("MEDIO", "Médio (10-20kg)"),
                            ("GRANDE", "Grande (20-40kg)"),
                            ("GIGANTE", "Gigante (acima de 40kg)"),
                        ],
                        max_length=10,
                        verbose_name="Porte",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="pets/%Y/%m/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True,
                        help_text="Alergias, medicações, comportamento, etc.",
                        verbose_name="Observações",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "db_table": "pets",
                "ordering": ["cliente", "nome"],
                "indexes": [
                    models.Index(
                        fields=["cliente", "ativo"], name="pets_cliente_f9c641_idx"
                    ),
                    models.Index(fields=["especie"], name="pets_especie_9a791d_idx"),
                ],
            },
        ),
    ]
