# Generated by Django 4.2.11 on 2026-03-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="data_nascimento",
            field=models.DateField(
                blank=True,
                help_text="Data de nascimento do pet",
                null=True,
                verbose_name="Data de Nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to="pets/fotos/", verbose_name="Foto"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="idade",
            field=models.PositiveIntegerField(
                blank=True, help_text="Idade em anos", null=True, verbose_name="Idade"
            ),
        ),
    ]
